/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Customer;
import Model.Demand;
import java.awt.Color;
import View.ViewDesign.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.SwingUtilities;

/**
 *
 * @author Bhop
 */
public class CustomerMainPage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerMainPage
     */
    /*
    String[] citys ={"Adana","Adıyaman", "Afyon", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin",
            "Aydın", "Balıkesir","Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale",
            "Çankırı", "Çorum","Denizli","Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum ", "Eskişehir",
            "Gaziantep", "Giresun","Gümüşhane", "Hakkari", "Hatay", "Isparta", "Mersin", "İstanbul", "İzmir",
            "Kars", "Kastamonu", "Kayseri","Kırklareli", "Kırşehir", "Kocaeli", "Konya", "Kütahya ", "Malatya",
            "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Rize", "Sakarya",
            "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon  ", "Tunceli", "Şanlıurfa", "Uşak",
            "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt ", "Karaman", "Kırıkkale", "Batman", "Şırnak",
            "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük ", "Kilis", "Osmaniye ", "Düzce"};
    
    String[] country = {"Türkiye","Almanya","Rusya","İngiltere"};
     */
    public CustomerMainPage() {
        initComponents();
    }
    String[] capasity = {"50m³", "60m³", "70m³", "80m³", "90m³", "100m³", "110m³"};
    private boolean isActiveWork = true;

    public CustomerMainPage(Customer customer) {

        initComponents();
        email.setText(customer.getEmail());
        name.setText(customer.getName());
        phoneNo.setText(customer.getPhone());
        password.setText(customer.getPassword());
        welcome_name.setText("Hoşgeldin " + customer.getName().toUpperCase());
        if (isActiveWork == false) {
            customerTabbed.remove(3);
        } else {

        }

        CountryAndCity asd = new CountryAndCity();

        for (int i = 0; i < asd.phoneCountryCode.length; i++) {
            phoneCode.addItem(asd.phoneCountryCode[i]);
        }
        //getContentPane().setBackground(new Color);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(51, 51, 51));
        // jScrollPane2.setVerticalScrollBar(new ScrollBar());
        for (int i = 0; i < asd.country.length; i++) {
            countryComboBox.addItem(asd.country[i]);
        }

        for (int i = 0; i < asd.productType.length; i++) {
            prductTypeComboBox.addItem(asd.productType[i]);
        }

        for (int i = 0; i < capasity.length; i++) {
            productCapasityComboBox.addItem(capasity[i]);
        }

        demandButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (product_expl.getText().equals("") || productPriceTF.getText().equals("") || adressTA.getText().equals("")) {
                    //Error Message
                } else {
                    try {
                        Demand demand = new Demand();
                        demand.insertDemand(customer.getId(), customer.getName(),prductTypeComboBox.getSelectedItem().toString(),
                                product_expl.getText(), productCapasityComboBox.getSelectedItem().toString(),
                                 productPriceTF.getText(),currentCityComboBox.getSelectedItem().toString(),
                                 countryComboBox.getSelectedItem().toString(), cityComboBox.getSelectedItem().toString(),
                                adressTA.getText(), "True");
                    } catch (SQLException ex) {
                        System.out.println("Talep Oluşturulamadı.");
                        ex.printStackTrace();
                    }
                }
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerTabbed = new View.ViewDesign.MaterialTabbed();
        mainPanel = new View.ViewDesign.CustomPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new View.ViewDesign.Table();
        accountPanel = new View.ViewDesign.CustomPanel();
        email = new View.ViewDesign.TextField();
        name = new View.ViewDesign.TextField();
        phoneNo = new View.ViewDesign.TextField();
        password = new View.ViewDesign.PasswordField();
        saveButton = new View.ViewDesign.CustomButton();
        editButton = new View.ViewDesign.CustomButton();
        loginButton2 = new View.ViewDesign.CustomButton();
        phoneCode = new View.ViewDesign.Combobox();
        createDemandPanel = new View.ViewDesign.CustomPanel();
        textAreaScroll1 = new View.ViewDesign.TextAreaScroll();
        product_expl = new View.ViewDesign.TextArea();
        productCapasityComboBox = new View.ViewDesign.Combobox();
        countryComboBox = new View.ViewDesign.Combobox();
        cityComboBox = new View.ViewDesign.Combobox();
        textAreaScroll2 = new View.ViewDesign.TextAreaScroll();
        adressTA = new View.ViewDesign.TextArea();
        demandButton = new View.ViewDesign.CustomButton();
        productPriceTF = new View.ViewDesign.TextField();
        prductTypeComboBox = new View.ViewDesign.Combobox();
        currentCityComboBox = new View.ViewDesign.Combobox();
        workPanel = new View.ViewDesign.CustomPanel();
        jLabel1 = new javax.swing.JLabel();
        connectionIcon = new javax.swing.JLabel();
        welcome_name = new javax.swing.JLabel();
        Create = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        customerTabbed.setBackground(new java.awt.Color(0, 0, 0));
        customerTabbed.setForeground(new java.awt.Color(255, 255, 255));
        customerTabbed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customerTabbed.setPreferredSize(new java.awt.Dimension(820, 450));

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainPanel.setRoundBottomLeft(20);
        mainPanel.setRoundBottomRight(20);

        table1.setBackground(new java.awt.Color(51, 51, 51));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Tarık CUCUN", "5000", "3", "4,7", "3.11.2022"},
                {"2", "Mehmet Sağlam", "3000", "2", "3,5", "2.11.2022"},
                {"3", "Emre Selim", "6000", "10", "4,9", "3.11.2022"},
                {"4", "Hasan Temiz", "2000", "1", "0,5", "28.10.2022"},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ad & Soyad", "Teklif Fiyat", "Tecrübe Yılı", "Puan", "Tarih"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        customerTabbed.addTab("Anasayfa", new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_homeWhite_32.png")), mainPanel); // NOI18N

        accountPanel.setBackground(new java.awt.Color(51, 51, 51));
        accountPanel.setRoundBottomLeft(20);
        accountPanel.setRoundBottomRight(20);

        email.setBackground(new java.awt.Color(51, 51, 51));
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setLabelText("Email");
        email.setLineColor(new java.awt.Color(255, 255, 255));

        name.setBackground(new java.awt.Color(51, 51, 51));
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setLabelText("Ad & Soyad");
        name.setLineColor(new java.awt.Color(255, 255, 255));

        phoneNo.setBackground(new java.awt.Color(51, 51, 51));
        phoneNo.setForeground(new java.awt.Color(255, 255, 255));
        phoneNo.setLabelText("Telefon");
        phoneNo.setLineColor(new java.awt.Color(255, 255, 255));
        phoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNoKeyTyped(evt);
            }
        });

        password.setBackground(new java.awt.Color(51, 51, 51));
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setAdressEye("/WhiteIcon/eye.png");
        password.setAdressEyeHide("/WhiteIcon/hideEye.png");
        password.setLabelText("Şifre");
        password.setLineColor(new java.awt.Color(255, 255, 255));
        password.setShowAndHide(true);

        saveButton.setBackground(new java.awt.Color(51, 51, 51));
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_save_16.png"))); // NOI18N
        saveButton.setActionCommand("Kaydet");
        saveButton.setAlignmentX(0.5F);
        saveButton.setBorderColor(new java.awt.Color(255, 255, 255));
        saveButton.setColor(new java.awt.Color(51, 51, 51));
        saveButton.setColorActive(new java.awt.Color(0, 0, 0));
        saveButton.setColorClick(new java.awt.Color(102, 102, 102));
        saveButton.setColorDisable(java.awt.Color.white);
        saveButton.setColorOver(new java.awt.Color(255, 255, 255));
        saveButton.setLabel("Kaydet");
        saveButton.setRadius(20);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(51, 51, 51));
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_edit_16.png"))); // NOI18N
        editButton.setText("Düzenle");
        editButton.setAlignmentX(0.5F);
        editButton.setBorderColor(new java.awt.Color(255, 255, 255));
        editButton.setColor(new java.awt.Color(51, 51, 51));
        editButton.setColorActive(new java.awt.Color(0, 0, 0));
        editButton.setColorClick(new java.awt.Color(102, 102, 102));
        editButton.setColorDisable(java.awt.Color.white);
        editButton.setColorOver(new java.awt.Color(255, 255, 255));
        editButton.setRadius(20);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        loginButton2.setBackground(new java.awt.Color(51, 51, 51));
        loginButton2.setForeground(new java.awt.Color(255, 255, 255));
        loginButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_remove_16.png"))); // NOI18N
        loginButton2.setAlignmentX(0.5F);
        loginButton2.setBorderColor(new java.awt.Color(255, 255, 255));
        loginButton2.setColor(new java.awt.Color(51, 51, 51));
        loginButton2.setColorActive(new java.awt.Color(0, 0, 0));
        loginButton2.setColorClick(new java.awt.Color(102, 102, 102));
        loginButton2.setColorDisable(java.awt.Color.white);
        loginButton2.setColorOver(new java.awt.Color(255, 255, 255));
        loginButton2.setLabel("Hesabı Sil");
        loginButton2.setRadius(20);
        loginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton2ActionPerformed(evt);
            }
        });

        phoneCode.setBackground(new java.awt.Color(51, 51, 51));
        phoneCode.setForeground(new java.awt.Color(255, 255, 255));
        phoneCode.setLabeText("Kod");
        phoneCode.setLineColor(new java.awt.Color(0, 0, 0));
        phoneCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanelLayout.createSequentialGroup()
                        .addComponent(phoneCode, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(407, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanelLayout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(phoneCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        customerTabbed.addTab("Profil", new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_customer_32_1.png")), accountPanel); // NOI18N

        createDemandPanel.setBackground(new java.awt.Color(51, 51, 51));
        createDemandPanel.setRoundBottomLeft(20);
        createDemandPanel.setRoundBottomRight(20);

        textAreaScroll1.setBackground(new java.awt.Color(51, 51, 51));
        textAreaScroll1.setLabelText("Ürün Adı & Açıklama");
        textAreaScroll1.setLineColor(new java.awt.Color(255, 255, 255));

        product_expl.setBackground(new java.awt.Color(51, 51, 51));
        product_expl.setColumns(20);
        product_expl.setForeground(new java.awt.Color(255, 255, 255));
        product_expl.setRows(5);
        textAreaScroll1.setViewportView(product_expl);

        productCapasityComboBox.setBackground(new java.awt.Color(51, 51, 51));
        productCapasityComboBox.setForeground(new java.awt.Color(255, 255, 255));
        productCapasityComboBox.setLabeText("Ürün Kapasite");
        productCapasityComboBox.setLineColor(new java.awt.Color(255, 255, 255));
        productCapasityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCapasityComboBoxActionPerformed(evt);
            }
        });

        countryComboBox.setBackground(new java.awt.Color(51, 51, 51));
        countryComboBox.setForeground(new java.awt.Color(255, 255, 255));
        countryComboBox.setLabeText("Gideceği Ülke");
        countryComboBox.setLineColor(new java.awt.Color(255, 255, 255));
        countryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryComboBoxActionPerformed(evt);
            }
        });

        cityComboBox.setBackground(new java.awt.Color(51, 51, 51));
        cityComboBox.setForeground(new java.awt.Color(255, 255, 255));
        cityComboBox.setLabeText("Gideceği Şehir");
        cityComboBox.setLineColor(new java.awt.Color(255, 255, 255));

        textAreaScroll2.setBackground(new java.awt.Color(51, 51, 51));
        textAreaScroll2.setLabelText("Açık Adres");
        textAreaScroll2.setLineColor(new java.awt.Color(255, 255, 255));

        adressTA.setBackground(new java.awt.Color(51, 51, 51));
        adressTA.setColumns(20);
        adressTA.setForeground(new java.awt.Color(255, 255, 255));
        adressTA.setRows(5);
        adressTA.setCaretColor(new java.awt.Color(255, 255, 255));
        textAreaScroll2.setViewportView(adressTA);

        demandButton.setForeground(new java.awt.Color(255, 255, 255));
        demandButton.setText("Teklif Ver");
        demandButton.setBorderColor(new java.awt.Color(255, 255, 255));
        demandButton.setColor(new java.awt.Color(51, 51, 51));
        demandButton.setColorActive(new java.awt.Color(0, 0, 0));
        demandButton.setColorClick(new java.awt.Color(102, 102, 102));
        demandButton.setColorDisable(new java.awt.Color(255, 255, 255));
        demandButton.setColorOver(new java.awt.Color(255, 255, 255));
        demandButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        demandButton.setRadius(20);

        productPriceTF.setBackground(new java.awt.Color(51, 51, 51));
        productPriceTF.setForeground(new java.awt.Color(255, 255, 255));
        productPriceTF.setLabelText("Fiyat");
        productPriceTF.setLineColor(new java.awt.Color(255, 255, 255));

        prductTypeComboBox.setBackground(new java.awt.Color(51, 51, 51));
        prductTypeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        prductTypeComboBox.setLabeText("Ürün Tip");
        prductTypeComboBox.setLineColor(new java.awt.Color(255, 255, 255));

        currentCityComboBox.setBackground(new java.awt.Color(51, 51, 51));
        currentCityComboBox.setForeground(new java.awt.Color(255, 255, 255));
        currentCityComboBox.setLabeText("Bulunduğu Şehir");
        currentCityComboBox.setLineColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout createDemandPanelLayout = new javax.swing.GroupLayout(createDemandPanel);
        createDemandPanel.setLayout(createDemandPanelLayout);
        createDemandPanelLayout.setHorizontalGroup(
            createDemandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createDemandPanelLayout.createSequentialGroup()
                .addGroup(createDemandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createDemandPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(createDemandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textAreaScroll2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(createDemandPanelLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(createDemandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(demandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)))
                .addGroup(createDemandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productCapasityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prductTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        createDemandPanelLayout.setVerticalGroup(
            createDemandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createDemandPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createDemandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createDemandPanelLayout.createSequentialGroup()
                        .addComponent(textAreaScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAreaScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(productPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createDemandPanelLayout.createSequentialGroup()
                        .addComponent(currentCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productCapasityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prductTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(demandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        customerTabbed.addTab("İlan Ekle", new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_PlusWhite_32.png")), createDemandPanel); // NOI18N

        workPanel.setBackground(new java.awt.Color(51, 51, 51));
        workPanel.setRoundBottomLeft(20);
        workPanel.setRoundBottomRight(20);
        workPanel.setRoundTopLeft(20);
        workPanel.setRoundTopRight(20);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Devam Eden iş yok...");

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        customerTabbed.addTab("Devam Eden İş", new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_truck_32_1.png")), workPanel); // NOI18N

        connectionIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connectionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_connected_16.png"))); // NOI18N

        welcome_name.setForeground(new java.awt.Color(255, 255, 255));
        welcome_name.setText("jLabel2");

        Create.setBackground(new java.awt.Color(153, 153, 153));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Home_16.png"))); // NOI18N
        jMenu1.setText("Ana Sayfa");
        Create.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_person_16.png"))); // NOI18N
        jMenu3.setText("Hesap");
        Create.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Plus_16.png"))); // NOI18N
        jMenu2.setText("İlan Ekle");
        jMenu2.setIconTextGap(0);
        Create.add(jMenu2);

        setJMenuBar(Create);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerTabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(welcome_name, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(connectionIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(connectionIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(welcome_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerTabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryComboBoxActionPerformed
        CountryAndCity asd = new CountryAndCity();
        name.setEnabled(false);

        email.setEnabled(false);
        password.setEnabled(false);
        phoneNo.setEnabled(false);

        phoneCode.setEnabled(false);
        if (countryComboBox.getSelectedIndex() == 0) {
            cityComboBox.removeAllItems();
            currentCityComboBox.removeAllItems();
            for (String turkeyCity : asd.turkeyCitys) {
                cityComboBox.addItem(turkeyCity);
            }
            for (String turkeyCity : asd.turkeyCitys) {
                currentCityComboBox.addItem(turkeyCity);
            }
        }
        if (countryComboBox.getSelectedIndex() == 1) {
            cityComboBox.removeAllItems();
            currentCityComboBox.removeAllItems();
            for (String germanyCity : asd.germanyCitys) {
                cityComboBox.addItem(germanyCity);
            }
            for (String germanyCity : asd.germanyCitys) {
                currentCityComboBox.addItem(germanyCity);
            }
        }
        if (countryComboBox.getSelectedIndex() == 2) {
            cityComboBox.removeAllItems();
            currentCityComboBox.removeAllItems();
            for (int i = 0; i < asd.rusianCitys.length; i++) {

                cityComboBox.addItem(asd.rusianCitys[i]);
            }
            for (int i = 0; i < asd.rusianCitys.length; i++) {
                currentCityComboBox.addItem(asd.rusianCitys[i]);
            }
        }
        if (countryComboBox.getSelectedIndex() == 3) {
            cityComboBox.removeAllItems();
            currentCityComboBox.removeAllItems();
            for (int i = 0; i < asd.englandCitys.length; i++) {

                cityComboBox.addItem(asd.englandCitys[i]);
            }
            for (String englandCity : asd.englandCitys) {
                currentCityComboBox.addItem(englandCity);
            }
        }
    }//GEN-LAST:event_countryComboBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        //CustomerMainPage cmp = new CustomerMainPage();
        //cmp.setVisible(true);
        TruckMainPage tmp = new TruckMainPage(null);
        tmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed
    private boolean state = false;
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed

        if (state == false) {
            name.setEnabled(true);
            email.setEnabled(true);
            password.setEnabled(true);
            phoneNo.setEnabled(true);

            phoneCode.setEnabled(true);
            state = true;
        } else {

            name.setEnabled(false);
            email.setEnabled(false);
            password.setEnabled(false);
            phoneNo.setEnabled(false);

            phoneCode.setEnabled(false);
            state = false;
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void loginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButton2ActionPerformed

    private void phoneCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneCodeActionPerformed

    private void phoneNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoKeyTyped
        char c = evt.getKeyChar();
        int tLength = phoneNo.getText().length();
        if (!Character.isDigit(c) || tLength == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_phoneNoKeyTyped

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        if (evt.getClickCount() == 2) {
            MessageDialog obj = new MessageDialog(this, "Seçilen İş", "Bu işi kabul etmek istiyor musunuz ?");
            obj.setVisible(true);
        }
    }//GEN-LAST:event_table1MouseClicked

    private void productCapasityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCapasityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productCapasityComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMainPage(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Create;
    private View.ViewDesign.CustomPanel accountPanel;
    private View.ViewDesign.TextArea adressTA;
    private View.ViewDesign.Combobox cityComboBox;
    private javax.swing.JLabel connectionIcon;
    private View.ViewDesign.Combobox countryComboBox;
    private View.ViewDesign.CustomPanel createDemandPanel;
    private View.ViewDesign.Combobox currentCityComboBox;
    private View.ViewDesign.MaterialTabbed customerTabbed;
    private View.ViewDesign.CustomButton demandButton;
    private View.ViewDesign.CustomButton editButton;
    private View.ViewDesign.TextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private View.ViewDesign.CustomButton loginButton2;
    private View.ViewDesign.CustomPanel mainPanel;
    private View.ViewDesign.TextField name;
    private View.ViewDesign.PasswordField password;
    private View.ViewDesign.Combobox phoneCode;
    private View.ViewDesign.TextField phoneNo;
    private View.ViewDesign.Combobox prductTypeComboBox;
    private View.ViewDesign.Combobox productCapasityComboBox;
    private View.ViewDesign.TextField productPriceTF;
    private View.ViewDesign.TextArea product_expl;
    private View.ViewDesign.CustomButton saveButton;
    private View.ViewDesign.Table table1;
    private View.ViewDesign.TextAreaScroll textAreaScroll1;
    private View.ViewDesign.TextAreaScroll textAreaScroll2;
    private javax.swing.JLabel welcome_name;
    private View.ViewDesign.CustomPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
