/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Customer;
import Model.TruckOwner;
import Service.DBConnect;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javaswing.JavaSwing;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Bhop
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    DBConnect con;

    public RegisterPage() throws SQLException {
        this.setUndecorated(true);
        UIManager.put("TextField.caretForeground", Color.black);
        UIManager.put("PasswordField.caretForeground", Color.black);
        initComponents();

        //DATABASE 
        con = new DBConnect();
        getContentPane().setBackground(new Color(51, 51, 51));
        setLocationRelativeTo(null);

        String[] phoneCountryCode = {"+90", "+49", "+7", "+44"};
        for (int i = 0; i < phoneCountryCode.length; i++) {
            phoneCode.addItem(phoneCountryCode[i]);
        }

        String[] plateCountryCode = {"TR", "D", "RUS", "GB"};

        String[] customerPhoneCountryCode = {"+90", "+49", "+7", "+44"};
        for (int i = 0; i < customerPhoneCountryCode.length; i++) {
            cPCode.addItem(customerPhoneCountryCode[i]);
        }

        JavaSwing js = new JavaSwing();
        if (js.connectionState == true) {
            connectionIcon.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_connected_16.png")));
            jLabel1.setText("Bağlandı");
            jLabel1.setForeground(Color.green);
        } else {
            connectionIcon.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_disconnected_16.png")));
            jLabel1.setText("Bağlantı Kesildi");
            jLabel1.setForeground(Color.red);
        }
        String typeValue;
        if (truckTabbed.getSelectedIndex() == 0) {
            typeValue = "Tır Şöfor";
        } else {
            typeValue = "Müşteri";
        }
        Customer c = new Customer();

        //c.insertCustomer(customerName.getText(), customerEmail.getText(), customerPhone.getText(), customerPassword.getText(), typeValue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        truckTabbed = new View.ViewDesign.MaterialTabbed();
        TruckRegisterPanel = new View.ViewDesign.CustomPanel();
        customPanel1 = new View.ViewDesign.CustomPanel();
        truckEmail = new View.ViewDesign.TextField();
        truckName = new View.ViewDesign.TextField();
        truckPhone = new View.ViewDesign.TextField();
        truckRegisterButton = new View.ViewDesign.CustomButton();
        truckPassword = new View.ViewDesign.PasswordField();
        phoneCode = new View.ViewDesign.Combobox();
        emailControlIcon1 = new javax.swing.JLabel();
        CustomerRegisterPanel = new View.ViewDesign.CustomPanel();
        registerPanel = new View.ViewDesign.CustomPanel();
        customerEmail = new View.ViewDesign.TextField();
        customerName = new View.ViewDesign.TextField();
        customerPhone = new View.ViewDesign.TextField();
        customerRegisterButton = new View.ViewDesign.CustomButton();
        customerPassword = new View.ViewDesign.PasswordField();
        cPCode = new View.ViewDesign.Combobox();
        emailControlIcon = new javax.swing.JLabel();
        phoneControlIcon = new javax.swing.JLabel();
        connectionIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        truckTabbed.setBackground(new java.awt.Color(51, 51, 51));
        truckTabbed.setForeground(new java.awt.Color(255, 255, 255));
        truckTabbed.setPreferredSize(new java.awt.Dimension(667, 407));

        TruckRegisterPanel.setBackground(new java.awt.Color(204, 204, 204));
        TruckRegisterPanel.setForeground(new java.awt.Color(51, 51, 51));
        TruckRegisterPanel.setToolTipText("");

        customPanel1.setBackground(new java.awt.Color(255, 255, 255));
        customPanel1.setForeground(new java.awt.Color(255, 255, 255));
        customPanel1.setRoundBottomLeft(20);
        customPanel1.setRoundBottomRight(20);
        customPanel1.setRoundTopLeft(20);
        customPanel1.setRoundTopRight(20);

        truckEmail.setLabelText("Email");
        truckEmail.setLineColor(new java.awt.Color(0, 0, 0));
        truckEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                truckEmailKeyReleased(evt);
            }
        });

        truckName.setLabelText("Ad & Soyad");
        truckName.setLineColor(new java.awt.Color(0, 0, 0));
        truckName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truckNameActionPerformed(evt);
            }
        });

        truckPhone.setCaretColor(new java.awt.Color(255, 255, 255));
        truckPhone.setLabelText("Telefon");
        truckPhone.setLineColor(new java.awt.Color(0, 0, 0));
        truckPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truckPhoneActionPerformed(evt);
            }
        });
        truckPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                truckPhoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                truckPhoneKeyTyped(evt);
            }
        });

        truckRegisterButton.setText("Kayıt Ol");
        truckRegisterButton.setBorderColor(new java.awt.Color(0, 0, 0));
        truckRegisterButton.setColorActive(java.awt.Color.white);
        truckRegisterButton.setColorClick(new java.awt.Color(102, 102, 102));
        truckRegisterButton.setColorDisable(new java.awt.Color(0, 0, 0));
        truckRegisterButton.setColorOver(new java.awt.Color(0, 0, 0));
        truckRegisterButton.setRadius(20);
        truckRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truckRegisterButtonActionPerformed(evt);
            }
        });

        truckPassword.setAdressEye("/WhiteIcon/eyeDark.png");
        truckPassword.setAdressEyeHide("/WhiteIcon/hideEyeDark.png");
        truckPassword.setLabelText("Şifre");
        truckPassword.setLineColor(new java.awt.Color(0, 0, 0));
        truckPassword.setShowAndHide(true);

        phoneCode.setLabeText("Kod");
        phoneCode.setLineColor(new java.awt.Color(0, 0, 0));
        phoneCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customPanel1Layout = new javax.swing.GroupLayout(customPanel1);
        customPanel1.setLayout(customPanel1Layout);
        customPanel1Layout.setHorizontalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanel1Layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(truckName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanel1Layout.createSequentialGroup()
                            .addComponent(phoneCode, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(truckPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(truckPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(truckEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(emailControlIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(truckRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        customPanel1Layout.setVerticalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanel1Layout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailControlIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(customPanel1Layout.createSequentialGroup()
                        .addComponent(truckEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(truckName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(truckPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(truckPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(truckRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout TruckRegisterPanelLayout = new javax.swing.GroupLayout(TruckRegisterPanel);
        TruckRegisterPanel.setLayout(TruckRegisterPanelLayout);
        TruckRegisterPanelLayout.setHorizontalGroup(
            TruckRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TruckRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TruckRegisterPanelLayout.setVerticalGroup(
            TruckRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TruckRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        truckTabbed.addTab("Tır Sahibi Kayıt", new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_truck_32_1.png")), TruckRegisterPanel); // NOI18N

        CustomerRegisterPanel.setBackground(new java.awt.Color(204, 204, 204));
        CustomerRegisterPanel.setForeground(new java.awt.Color(255, 255, 255));
        CustomerRegisterPanel.setPreferredSize(new java.awt.Dimension(667, 407));

        registerPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerPanel.setRoundBottomLeft(20);
        registerPanel.setRoundBottomRight(20);
        registerPanel.setRoundTopLeft(20);
        registerPanel.setRoundTopRight(20);

        customerEmail.setLabelText("Email");
        customerEmail.setLineColor(new java.awt.Color(0, 0, 0));
        customerEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerEmailKeyReleased(evt);
            }
        });

        customerName.setLabelText("Ad & Soyad");
        customerName.setLineColor(new java.awt.Color(0, 0, 0));
        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });

        customerPhone.setLabelText("Telefon");
        customerPhone.setLineColor(new java.awt.Color(0, 0, 0));
        customerPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerPhoneActionPerformed(evt);
            }
        });
        customerPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerPhoneKeyTyped(evt);
            }
        });

        customerRegisterButton.setText("Kayıt Ol");
        customerRegisterButton.setBorderColor(new java.awt.Color(0, 0, 0));
        customerRegisterButton.setColorActive(java.awt.Color.white);
        customerRegisterButton.setColorClick(new java.awt.Color(102, 102, 102));
        customerRegisterButton.setColorDisable(new java.awt.Color(0, 0, 0));
        customerRegisterButton.setColorOver(new java.awt.Color(0, 0, 0));
        customerRegisterButton.setRadius(20);
        customerRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRegisterButtonActionPerformed(evt);
            }
        });

        customerPassword.setAdressEye("/WhiteIcon/eyeDark.png");
        customerPassword.setAdressEyeHide("/WhiteIcon/hideEyeDark.png");
        customerPassword.setLabelText("Şifre");
        customerPassword.setLineColor(new java.awt.Color(0, 0, 0));
        customerPassword.setShowAndHide(true);

        cPCode.setLabeText("Kod");
        cPCode.setLineColor(new java.awt.Color(0, 0, 0));
        cPCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(customerRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPanelLayout.createSequentialGroup()
                                .addComponent(cPCode, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(customerEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailControlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneControlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(168, 168, 168))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailControlIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneControlIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cPCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout CustomerRegisterPanelLayout = new javax.swing.GroupLayout(CustomerRegisterPanel);
        CustomerRegisterPanel.setLayout(CustomerRegisterPanelLayout);
        CustomerRegisterPanelLayout.setHorizontalGroup(
            CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CustomerRegisterPanelLayout.setVerticalGroup(
            CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        truckTabbed.addTab("Müşteri Kayıt", new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_customer_32_1.png")), CustomerRegisterPanel); // NOI18N

        connectionIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connectionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectIcon/icons8_connected_dark_16.png"))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("Bağlantı Kesildi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(truckTabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connectionIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectionIcon)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(truckTabbed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameActionPerformed

    private void customerPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerPhoneActionPerformed

    private void customerRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRegisterButtonActionPerformed

        
        Customer c = new Customer();

        if (!customerPassword.getText().equals("") || !customerEmail.getText().equals("")) {

            try {

                ResultSet rs = con.stmt.executeQuery("CALL read_customer");
                while (rs.next()) {
                    if (customerEmail.getText().equals(rs.getString("email"))) {
                        System.out.println("Invalid Email");
                        System.out.println("yukari");
                        break;
                    }
                }

                try {
                    c.insertCustomer(customerEmail.getText(), customerName.getText(), cPCode.getSelectedItem().toString() + " " + customerPhone.getText(),
                            customerPassword.getText());

                    LoginPage loginPage = new LoginPage();
                    loginPage.setVisible(true);
                    this.dispose();
                    //MsgDialog msg = new MsgDialog(this, "Başarılı", "Başarılı bir şekilde kayıt oldunuz", 0, MsgDialog.SelectedIcon.SUCCESS_ICON);
                    //msg.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
                    MsgDialog msg = new MsgDialog(this, "Hata", "Lütfen sonra tekrar deneyin", 0, MsgDialog.SelectedIcon.WARNING_ICON);
                    msg.setVisible(true);
                }

            } catch (SQLException e) {
                System.out.println("Invalid Email");
                MsgDialog msg = new MsgDialog(this, "Hata", "Bu email kullanılıyor", 0, MsgDialog.SelectedIcon.WARNING_ICON);
                msg.setVisible(true);
            }
        } else {
            //Error
            MsgDialog msg = new MsgDialog(this, "Hata", "Lütfen gerekli alanları doldurun", 0, MsgDialog.SelectedIcon.WARNING_ICON);
            msg.setVisible(true);

        }


    }//GEN-LAST:event_customerRegisterButtonActionPerformed

    private void customerPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerPhoneKeyTyped
        char c = evt.getKeyChar();
        int tLength = customerPhone.getText().length();
        if (!Character.isDigit(c) || tLength == 10) {
            evt.consume();
        }

        //DBConnect con = new DBConnect();
        //phoneControlIcon.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_ok_16.png")));
        /*
        try {
            ResultSet rs = con.stmt.executeQuery("CALL readCustomer");
            while(rs.next()){
                if(customerPhone.getText().equals(rs.getString("telefon"))){
                    //System.out.println("Aynı kullanıcıdan var");
                    phoneControlIcon.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_cancel_16.png")));
                }else{
                    phoneControlIcon.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_ok_16.png")));
                }//5412352342
                
                //System.out.println("email : "+rs.getString("email"));
                //System.out.println("password : "+rs.getString("sifre"));
            }
        } catch (SQLException e) {
            System.out.println("No data");
            e.printStackTrace();
        }
         */

    }//GEN-LAST:event_customerPhoneKeyTyped

    private void cPCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPCodeActionPerformed

    private void phoneCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneCodeActionPerformed

    private void truckPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_truckPhoneKeyTyped
        char c = evt.getKeyChar();
        int tLength = truckPhone.getText().length();
        if (!Character.isDigit(c) || tLength == 10) {
            evt.consume();
        }

    }//GEN-LAST:event_truckPhoneKeyTyped

    private void truckPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_truckPhoneKeyPressed
        /*
        String value = truckPhone.getText();
        int l = value.length();

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' ){
            truckPhone.setEditable(true);

        }else{
            truckPhone.setEditable(false);
        }
         */

    }//GEN-LAST:event_truckPhoneKeyPressed

    private void truckPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truckPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_truckPhoneActionPerformed

    private void truckNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truckNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_truckNameActionPerformed
    private static final String EMAIL_PATTERN
            = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{3})$";
    private void customerEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerEmailKeyReleased

        emailControlIcon.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_cancel_16.png")));
        try {
            ResultSet rs = con.stmt.executeQuery("CALL read_customer");
            while (rs.next()) {
                //System.out.println(rs.getString("email"));
                if (customerEmail.getText().equals(rs.getString("email")) || !customerEmail.getText().matches(EMAIL_PATTERN)) {
                    //System.out.println("Aynı kullanıcıdan var");
                    emailControlIcon.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_cancel_16.png")));
                    System.out.println("----");
                    System.out.println(rs.getString("email"));
                    break;
                } else {
                    emailControlIcon.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_ok_16.png")));

                }

                //System.out.println("email : "+rs.getString("email"));
                //System.out.println("password : "+rs.getString("sifre"));
            }
        } catch (SQLException e) {
            System.out.println("No data");
            e.printStackTrace();
        }

    }//GEN-LAST:event_customerEmailKeyReleased

    private void truckRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truckRegisterButtonActionPerformed
        TruckOwner truckOwner = new TruckOwner();

        if (!truckPassword.getText().equals("") || !truckEmail.getText().equals("")) {

            try {

                ResultSet rs = con.stmt.executeQuery("CALL read_truck_owner");
                while (rs.next()) {
                    if (truckEmail.getText().equals(rs.getString("email"))) {
                        System.out.println("Invalid Email");
                        System.out.println("yukari");
                        break;
                    }
                }

                try {
                    truckOwner.insertTruckOwner(truckEmail.getText(), truckName.getText(), phoneCode.getSelectedItem().toString() + " " + truckPhone.getText(),
                            truckPassword.getText());

                    LoginPage loginPage = new LoginPage();
                    loginPage.setVisible(true);
                    this.dispose();
                    //MsgDialog msg = new MsgDialog(this, "Başarılı", "Başarılı bir şekilde kayıt oldunuz", 0, MsgDialog.SelectedIcon.SUCCESS_ICON);
                    //msg.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
                    MsgDialog msg = new MsgDialog(this, "Hata", "Lütfen sonra tekrar deneyin", 0, MsgDialog.SelectedIcon.WARNING_ICON);
                    msg.setVisible(true);
                }

            } catch (SQLException e) {
                System.out.println("Invalid Email");
                MsgDialog msg = new MsgDialog(this, "Hata", "Bu email kullanılıyor", 0, MsgDialog.SelectedIcon.WARNING_ICON);
                msg.setVisible(true);
            }
        } else {
            //Error
            MsgDialog msg = new MsgDialog(this, "Hata", "Lütfen gerekli alanları doldurun", 0, MsgDialog.SelectedIcon.WARNING_ICON);
            msg.setVisible(true);

        }


    }//GEN-LAST:event_truckRegisterButtonActionPerformed

    private void truckEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_truckEmailKeyReleased
        emailControlIcon1.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_ok_16.png")));
        try {
            ResultSet rs = con.stmt.executeQuery("CALL read_truck_owner");
            while (rs.next()) {
                if (truckEmail.getText().equals(rs.getString("email")) || !truckEmail.getText().matches(EMAIL_PATTERN)) {
                    //System.out.println("Aynı kullanıcıdan var");
                    emailControlIcon1.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_cancel_16.png")));
                    break;
                } else {
                    emailControlIcon1.setIcon(new ImageIcon(getClass().getResource("/ProjectIcon/icons8_ok_16.png")));
                }

                //System.out.println("email : "+rs.getString("email"));
                //System.out.println("password : "+rs.getString("sifre"));
            }
        } catch (SQLException e) {
            System.out.println("No data");
            e.printStackTrace();
        }
    }//GEN-LAST:event_truckEmailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegisterPage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.ViewDesign.CustomPanel CustomerRegisterPanel;
    private View.ViewDesign.CustomPanel TruckRegisterPanel;
    private View.ViewDesign.Combobox cPCode;
    private javax.swing.JLabel connectionIcon;
    private View.ViewDesign.CustomPanel customPanel1;
    private View.ViewDesign.TextField customerEmail;
    private View.ViewDesign.TextField customerName;
    private View.ViewDesign.PasswordField customerPassword;
    private View.ViewDesign.TextField customerPhone;
    private View.ViewDesign.CustomButton customerRegisterButton;
    private javax.swing.JLabel emailControlIcon;
    private javax.swing.JLabel emailControlIcon1;
    private javax.swing.JLabel jLabel1;
    private View.ViewDesign.Combobox phoneCode;
    private javax.swing.JLabel phoneControlIcon;
    private View.ViewDesign.CustomPanel registerPanel;
    private View.ViewDesign.TextField truckEmail;
    private View.ViewDesign.TextField truckName;
    private View.ViewDesign.PasswordField truckPassword;
    private View.ViewDesign.TextField truckPhone;
    private View.ViewDesign.CustomButton truckRegisterButton;
    private View.ViewDesign.MaterialTabbed truckTabbed;
    // End of variables declaration//GEN-END:variables
}
